# Liste des villes avec région et département
cities = [
    # Oise
    {"city": "Beauvais", "region": "hauts-de-france", "department": "oise"},
    {"city": "Compiègne", "region": "hauts-de-france", "department": "oise"},
    {"city": "Creil", "region": "hauts-de-france", "department": "oise"},
    {"city": "Nogent-sur-Oise", "region": "hauts-de-france", "department": "oise"},
    {"city": "Senlis", "region": "hauts-de-france", "department": "oise"},
    {"city": "Montataire", "region": "hauts-de-france", "department": "oise"},
    {"city": "Clermont", "region": "hauts-de-france", "department": "oise"},
    {"city": "Méru", "region": "hauts-de-france", "department": "oise"},
    {"city": "Chantilly", "region": "hauts-de-france", "department": "oise"},
    {"city": "Gouvieux", "region": "hauts-de-france", "department": "oise"},
    {"city": "Pont-Sainte-Maxence", "region": "hauts-de-france", "department": "oise"},
    {"city": "Crépy-en-Valois", "region": "hauts-de-france", "department": "oise"},
    {"city": "Liancourt", "region": "hauts-de-france", "department": "oise"},
    # Somme
    {"city": "Amiens", "region": "hauts-de-france", "department": "somme"},
    {"city": "Abbeville", "region": "hauts-de-france", "department": "somme"},
    {"city": "Péronne", "region": "hauts-de-france", "department": "somme"},
    {"city": "Albert", "region": "hauts-de-france", "department": "somme"},
    {"city": "Doullens", "region": "hauts-de-france", "department": "somme"},
    {"city": "Rivery", "region": "hauts-de-france", "department": "somme"},
    {"city": "Longueau", "region": "hauts-de-france", "department": "somme"},
    {"city": "Ham", "region": "hauts-de-france", "department": "somme"},
    # Aisne
    {"city": "Saint-Quentin", "region": "hauts-de-france", "department": "aisne"},
    {"city": "Soissons", "region": "hauts-de-france", "department": "aisne"},
    {"city": "Laon", "region": "hauts-de-france", "department": "aisne"},
    {"city": "Château-Thierry", "region": "hauts-de-france", "department": "aisne"},
    {"city": "Tergnier", "region": "hauts-de-france", "department": "aisne"},
    {"city": "Chauny", "region": "hauts-de-france", "department": "aisne"},
    {"city": "Villeneuve-Saint-Germain", "region": "hauts-de-france", "department": "aisne"},
    {"city": "Hirson", "region": "hauts-de-france", "department": "aisne"},
    {"city": "Fère-en-Tardenois", "region": "hauts-de-france", "department": "aisne"},
]